### ISSUE TITLE
Password storage

### ISSUE THREAD

**Issue by entropia1** [hannesrauhe/lunchinator#241]
Currently, there is no possibility to appropriately store passwords entered in the settings. If we want to change this, there are multiple questions:

1. How do we specify a password setting? A special default value?
2. How do we access the password when needed? Does it reside in the `options` dict or do we have a specific getter that reads it on demand s.t. it is not stored in memory?
3. How do we store the password? There is the [keyring](https://pypi.python.org/pypi/keyring) package, I will have a look at it.
4. How are passwords identified? Especially database settings: Something like _Plugin Name_._Connection Name_._Setting Name_?

What do you think?

**Comment by hannesrauhe** [comment]
I recently merged 'nightly' into 'master'. I'll merge 'password' into 'nightly' now so I can test on all machines.

**Comment by hannesrauhe** [comment]
At least no immediate problems. Will close this issue.
